version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
platform: x64
clone_folder: c:\projects\uacme
build:
  project: Source/uacme.sln
  verbosity: normal
artifacts:
  - path: Akagi64.exe
    name: Akagi64
  - path: Fubuki64.dll
    name: Fubuki64
