version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
platform: x64
clone_folder: c:\projects\uacme
build:
  project: Source/uacme.sln
  verbosity: normal
artifacts:
  - path: Source\Akatsuki\output\x64\Release\Akatsuki64.dll
  - path: Source\Akagi\output\x64\Release\Akagi64.exe
  - path: Source\Fubuki\output\x64\Release\Fubuki64.dll
  - path: Source\Naka\output\x64\Release\Naka64.exe
  - path: Source\Yuubari\output\x64\Release\UacInfo64.exe
    name: Release
    type: zip
